// Long-form body copy per New Orleans neighborhood — used by
// new-orleans.$suburb.tsx to lift pages above the 700-word threshold.

export const SUBURB_BODIES: Record<string, string[]> = {
  "downtown-new-orleans": [
    "Downtown New Orleans runs along Poydras Street and Canal from the Superdome to the Mississippi — a dense professional core of law firms, accounting practices, hotel flags, convention-adjacent hospitality and financial services. Cash flow here tracks the convention calendar, the Superdome event cycle and the lunchtime rush from government offices. Rent and build-out costs along Poydras and Canal run materially above the metro average, which means working capital structure and bridge financing matter more here than in the suburbs.",
    "Drawbridge Lending has routed Downtown deals across three recurring patterns: professional-services partner buy-ins (often unsecured, structured around partner draw cycles), hotel PIPs when a flag requires a full renovation, and SBA 7(a) acquisition deals when established Downtown operators transition ownership. SBA 504 fits when a Poydras Street firm finally stops leasing and buys its own office floor. For event-driven food-and-beverage operators, working capital lines cover the gap between fixed lease costs and uneven monthly revenue tied to convention bookings and Superdome events.",
  ],
  "french-quarter": [
    "The French Quarter is the city's historic core — Bourbon Street bars, Royal Street antique galleries, boutique hotels on Chartres, and the unbroken tourist trade that makes it one of the highest-revenue-per-square-foot retail corridors in the South. Foot traffic is heavy and weekend-skewed, producing a revenue pattern more like a destination district than a neighborhood retail strip. Rent per square foot along the Bourbon and Royal corridors rivals anywhere in the metro.",
    "Drawbridge Lending routes Quarter financing around working capital lines that flex with festival seasons, SBA 7(a) for concept acquisitions, and bridge loans when a long-running establishment changes hands. Gallery Hop-driven retailers and boutique lodging operators benefit most from revenue-based financing — payments flex with the event-driven sales cycle rather than forcing a fixed monthly installment. For chef-driven concepts scaling from one to two locations, SBA 7(a) handles the acquisition cleanly at 10% down with goodwill financing included.",
  ],
  "garden-district": [
    "The Garden District stretches along St. Charles Avenue and Magazine Street — one of the city's most walkable retail corridors anchored by boutiques, chef-driven restaurants, design studios and professional offices. Operators here trend established and design-forward, with revenue patterns more consistent than the tourism-driven Quarter. Rent and build-out costs along Magazine are significant, but the customer base is affluent and year-round.",
    "Drawbridge Lending finances Garden District owners with SBA 7(a) acquisitions, equipment and working capital combos for restaurants, and revenue-based financing for design and creative firms. Succession deals are common here — second- or third-generation transitions of established Magazine Street boutiques and restaurants are among the most common Drawbridge closes in this corridor. For dental and medical practices in the District, SBA 7(a) handles partner buy-ins cleanly at rates that beat conventional practice financing.",
  ],
  "marigny": [
    "The Marigny sits just downriver from the Quarter — Frenchmen Street's live music clubs, independent bars, boutique lodging and the creative-class residential base that supports them. Revenue patterns here spike around Jazz Fest, Mardi Gras and Halloween, then flatten between peaks. The seasonal swing is sharper than in any other New Orleans district, which makes flexible working capital the single most important financing tool for Marigny operators.",
    "Drawbridge Lending finances Marigny operators with revolving working capital lines that absorb the seasonal swings, equipment financing for sound and production, and SBA 7(a) for concept acquisitions. Revenue-based financing suits Frenchmen Street bars and music venues particularly well — payments track the actual revenue curve rather than demanding a fixed monthly installment in a slow shoulder month. For boutique guesthouse operators, SBA 504 handles building acquisition at 10% down with the property as collateral.",
  ],
  "mid-city": [
    "Mid-City runs along Canal Street and Carrollton from the cemeteries to City Park — a deep base of family-owned restaurants, medical offices, trades and neighborhood retail. Operators here trend long-tenured and locally rooted, with solid underwriting profiles built on consistent community revenue. The City Park adjacency adds event-driven traffic around the New Orleans Museum of Art and the Fair Grounds Race Course.",
    "Drawbridge Lending routes Mid-City financing across SBA 7(a) for family-business successions, equipment loans for trades, and working capital lines for restaurants. HVAC, plumbing and electrical operators along the Canal corridor finance trucks and equipment with the rolling stock as collateral. For Carrollton-area restaurants and medical practices, SBA 7(a) handles partner buy-ins and acquisitions at competitive pricing when clean underwriting profiles clear the Preferred Lender pre-screen.",
  ],
  "uptown": [
    "Uptown stretches along St. Charles and Magazine from the Garden District to the Riverbend — home to Tulane, Loyola, Audubon Park and a thick base of upscale retail, professional offices and chef-driven restaurants. Operators here tend to be highly credentialed with clean underwriting profiles and a high fit for unsecured working capital, SBA acquisition deals and revenue-based products.",
    "Drawbridge Lending routes Uptown financing toward growth capital — hiring ramps, second-location builds and partner buy-ins. Maple Street law and accounting practices use unsecured working capital lines for growth without taking on a blanket UCC lien. For Riverbend restaurant groups scaling into a second concept, SBA 7(a) handles the acquisition cleanly. Dental and medical practices around Audubon Park are among the cleanest SBA underwriting profiles in the metro — stable revenue, predictable insurance cycles and an affluent patient base.",
  ],
  "bywater": [
    "Bywater sits downriver from the Marigny — a fast-gentrifying arts district of converted warehouses, independent restaurants, galleries and short-term rental properties. Operators here skew younger and entrepreneurial, with newer businesses that may carry thinner underwriting profiles but strong revenue trajectories. The Crescent Park riverfront and Studio Be anchor a growing destination draw for weekend visitors.",
    "Drawbridge Lending finances Bywater owners with revenue-based products, SBA Microloan programs for startups and working capital lines that grow with the business. Revenue-based financing suits Bywater's creative-economy operators particularly well — payments track actual revenue rather than demanding a fixed installment during a slow build phase. For Press Street gallery operators and boutique restaurateurs doing initial buildouts, SBA Microloans cover the early capital need without the full SBA 7(a) underwriting overhead.",
  ],
  "treme": [
    "Tremé is the oldest African American neighborhood in the United States — the birthplace of jazz, home of Congo Square, and a deep base of community-rooted restaurants, music venues and cultural institutions. Operators here often carry long histories but face access-to-capital gaps that traditional banks have not addressed. Drawbridge Lending is committed to closing that gap.",
    "Drawbridge Lending finances Tremé operators across SBA 7(a), SBA Microloans, community lender partnerships and unsecured working capital for established operators who have been underserved by conventional banks. Congo Square-area catering and event operators use working capital lines to bridge the gap between festival contract advances and actual event dates. Music venues on St. Claude and in the Armstrong Park corridor use SBA Microloans for renovation and equipment without the documentation burden of a full SBA 7(a) file.",
  ],
  "metairie": [
    "Metairie is Jefferson Parish's largest commercial node — Veterans Memorial Boulevard's medical corridor, Causeway Boulevard office parks, Lakeside Shopping Center and a deep base of professional services, restaurants and specialty retail. Operators here trend established and professionally licensed, with clean underwriting profiles that fit SBA 7(a) and unsecured working capital products cleanly.",
    "Drawbridge Lending routes Metairie deals through unsecured working capital lines, SBA 7(a) for medical and dental practice acquisitions, and SBA 504 for owner-occupied office purchases. Veterans Boulevard medical and dental practices are among the cleanest SBA underwriting profiles in the metro — stable revenue, predictable insurance cycles and an affluent patient base produce deals that clear the Preferred Lender pre-screen at the most competitive pricing tier. Financial services firms along Causeway use unsecured working capital lines for hiring and technology without the UCC blanket that would complicate their balance sheets.",
  ],
  "kenner": [
    "Kenner sits west of Metairie along I-10, anchored by Louis Armstrong International Airport — a strong base of logistics operators, airport-adjacent hospitality, family-owned trades and light industrial businesses. Operators here are often asset-heavy and underbanked relative to their revenue, which creates a high fit for equipment financing, SBA 7(a) and factoring structures.",
    "Drawbridge Lending routes Kenner deals around airport logistics, hospitality and the industrial corridor along Williams Boulevard. Freight and logistics operators at Armstrong use invoice factoring to convert airport contracts to same-day cash — the invoice is the collateral, not the balance sheet. HVAC and trades operators along the Williams corridor finance fleet refreshes with equipment loans, preserving operating cash for materials and payroll. For airport-adjacent hotels doing brand-mandated PIPs, SBA 504 or bridge-to-permanent structures handle the renovation at 10% down.",
  ],
};
