/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewOrleansRouteImport } from './routes/new-orleans'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyNowRouteImport } from './routes/apply-now'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PillarSlugRouteImport } from './routes/pillar.$slug'
import { Route as NewOrleansSuburbRouteImport } from './routes/new-orleans.$suburb'
import { Route as IndustrySlugRouteImport } from './routes/industry.$slug'
import { Route as NewOrleansSuburbPillarRouteImport } from './routes/new-orleans.$suburb.$pillar'

const NewOrleansRoute = NewOrleansRouteImport.update({
  id: '/new-orleans',
  path: '/new-orleans',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyNowRoute = ApplyNowRouteImport.update({
  id: '/apply-now',
  path: '/apply-now',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarSlugRoute = PillarSlugRouteImport.update({
  id: '/pillar/$slug',
  path: '/pillar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewOrleansSuburbRoute = NewOrleansSuburbRouteImport.update({
  id: '/$suburb',
  path: '/$suburb',
  getParentRoute: () => NewOrleansRoute,
} as any)
const IndustrySlugRoute = IndustrySlugRouteImport.update({
  id: '/industry/$slug',
  path: '/industry/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewOrleansSuburbPillarRoute = NewOrleansSuburbPillarRouteImport.update({
  id: '/$pillar',
  path: '/$pillar',
  getParentRoute: () => NewOrleansSuburbRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/new-orleans': typeof NewOrleansRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/new-orleans/$suburb': typeof NewOrleansSuburbRouteWithChildren
  '/pillar/$slug': typeof PillarSlugRoute
  '/new-orleans/$suburb/$pillar': typeof NewOrleansSuburbPillarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/new-orleans': typeof NewOrleansRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/new-orleans/$suburb': typeof NewOrleansSuburbRouteWithChildren
  '/pillar/$slug': typeof PillarSlugRoute
  '/new-orleans/$suburb/$pillar': typeof NewOrleansSuburbPillarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/new-orleans': typeof NewOrleansRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/new-orleans/$suburb': typeof NewOrleansSuburbRouteWithChildren
  '/pillar/$slug': typeof PillarSlugRoute
  '/new-orleans/$suburb/$pillar': typeof NewOrleansSuburbPillarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply-now'
    | '/contact'
    | '/new-orleans'
    | '/industry/$slug'
    | '/new-orleans/$suburb'
    | '/pillar/$slug'
    | '/new-orleans/$suburb/$pillar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply-now'
    | '/contact'
    | '/new-orleans'
    | '/industry/$slug'
    | '/new-orleans/$suburb'
    | '/pillar/$slug'
    | '/new-orleans/$suburb/$pillar'
  id:
    | '__root__'
    | '/'
    | '/apply-now'
    | '/contact'
    | '/new-orleans'
    | '/industry/$slug'
    | '/new-orleans/$suburb'
    | '/pillar/$slug'
    | '/new-orleans/$suburb/$pillar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyNowRoute: typeof ApplyNowRoute
  ContactRoute: typeof ContactRoute
  NewOrleansRoute: typeof NewOrleansRouteWithChildren
  IndustrySlugRoute: typeof IndustrySlugRoute
  PillarSlugRoute: typeof PillarSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-orleans': {
      id: '/new-orleans'
      path: '/new-orleans'
      fullPath: '/new-orleans'
      preLoaderRoute: typeof NewOrleansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-now': {
      id: '/apply-now'
      path: '/apply-now'
      fullPath: '/apply-now'
      preLoaderRoute: typeof ApplyNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillar/$slug': {
      id: '/pillar/$slug'
      path: '/pillar/$slug'
      fullPath: '/pillar/$slug'
      preLoaderRoute: typeof PillarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-orleans/$suburb': {
      id: '/new-orleans/$suburb'
      path: '/$suburb'
      fullPath: '/new-orleans/$suburb'
      preLoaderRoute: typeof NewOrleansSuburbRouteImport
      parentRoute: typeof NewOrleansRoute
    }
    '/industry/$slug': {
      id: '/industry/$slug'
      path: '/industry/$slug'
      fullPath: '/industry/$slug'
      preLoaderRoute: typeof IndustrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-orleans/$suburb/$pillar': {
      id: '/new-orleans/$suburb/$pillar'
      path: '/$pillar'
      fullPath: '/new-orleans/$suburb/$pillar'
      preLoaderRoute: typeof NewOrleansSuburbPillarRouteImport
      parentRoute: typeof NewOrleansSuburbRoute
    }
  }
}

interface NewOrleansSuburbRouteChildren {
  NewOrleansSuburbPillarRoute: typeof NewOrleansSuburbPillarRoute
}

const NewOrleansSuburbRouteChildren: NewOrleansSuburbRouteChildren = {
  NewOrleansSuburbPillarRoute: NewOrleansSuburbPillarRoute,
}

const NewOrleansSuburbRouteWithChildren =
  NewOrleansSuburbRoute._addFileChildren(NewOrleansSuburbRouteChildren)

interface NewOrleansRouteChildren {
  NewOrleansSuburbRoute: typeof NewOrleansSuburbRouteWithChildren
}

const NewOrleansRouteChildren: NewOrleansRouteChildren = {
  NewOrleansSuburbRoute: NewOrleansSuburbRouteWithChildren,
}

const NewOrleansRouteWithChildren = NewOrleansRoute._addFileChildren(
  NewOrleansRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyNowRoute: ApplyNowRoute,
  ContactRoute: ContactRoute,
  NewOrleansRoute: NewOrleansRouteWithChildren,
  IndustrySlugRoute: IndustrySlugRoute,
  PillarSlugRoute: PillarSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
